# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.hostname = "dev-host"
  config.vm.box = "ubuntu/xenial64"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "dev"
    vb.gui = true
    vb.memory = 10240
  end

  config.vm.provision "shell", "path": "script2.sh"
end