# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.hostname = "prod"
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  config.vm.synced_folder "data/", "/vagrant_data/", type: "virtualbox"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "prod"
    vb.gui = true
    vb.memory = 10240
  end

  config.vm.provision "shell", "path": "script.sh"
end
