# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.hostname = "prod"
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.network "public_network", bridge: "Intel(R) Ethernet Connection (2) I219-V"
  config.vm.synced_folder "data/", "/vagrant_data/", type: "virtualbox"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "prod"
    vb.gui = true
    vb.memory = 1024
  end

  config.vm.provision "shell", "path": "script.sh"
end
