# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.hostname = "dev-host"
  config.vm.box = "peru/ubuntu-18.04-desktop-amd64"
  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  config.vm.synced_folder "data/", "/vagrant_data/"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "dev"
    vb.gui = true
    vb.memory = 10240
  end

  config.vm.provision "shell", "path": "script.sh"
end
